import Header from "@/components/Header";
import SocialButtons from "@/components/SocialButtons";
import HeroSection from "@/components/HeroSection";
import NewsCard from "@/components/NewsCard";
import NewsCardSkeleton from "@/components/NewsCardSkeleton";
import SectionHeader from "@/components/SectionHeader";
import RotatingHeadlines from "@/components/RotatingHeadlines";
import Footer from "@/components/Footer";
import LazyAd from "@/components/LazyAd";
import { NewsItem, CategoryType } from "@/data/newsData";
import { useEffect, useState } from "react";
import { usePullToRefresh } from "@/hooks/usePullToRefresh";
import { useInfiniteScroll } from "@/hooks/useInfiniteScroll";
import ReadProgressBar from "@/components/ReadProgressBar";
=======
import Header from "@/components/Header";
import SocialButtons from "@/components/SocialButtons";
import SocialBar from "@/components/SocialBar";
import HeroSection from "@/components/HeroSection";
import NewsCard from "@/components/NewsCard";
import NewsCardSkeleton from "@/components/NewsCardSkeleton";
import SectionHeader from "@/components/SectionHeader";
import RotatingHeadlines from "@/components/RotatingHeadlines";
import Footer from "@/components/Footer";
import LazyAd from "@/components/LazyAd";
import SearchBar from "@/components/SearchBar";
import { NewsItem, CategoryType } from "@/data/newsData";
import { useEffect, useState } from "react";
import { usePullToRefresh } from "@/hooks/usePullToRefresh";
import { useInfiniteScroll } from "@/hooks/useInfiniteScroll";
import ReadProgressBar from "@/components/ReadProgressBar";
